### PR TITLE
2: Add unit tests and create github CI

### PR DESCRIPTION
**Pull request by sugat009**

### CODE REVIEW

**Review by aj3sh — CHANGES_REQUESTED** [review]
@sugat009, I have added some feedback. Please check.

**Comment by aj3sh** [comment]
Let's remember to exclude `django_nepali_example` from `setup.py` in the future.

**Comment by sugat009** [comment]
@aj3sh Requested changes have been incorporated.

**Review by aj3sh — APPROVED** [review]
Looks good.

**Pull request merged**
